#! /usr/bin/env node

const { execSync } = require('child_process');

const options = { encoding: 'utf-8', stdio : 'pipe' };

console.log('Converting issue into pull request');

const currentBranch = execSync('git branch | grep \\*', options);
const branch = currentBranch.slice(2, -1);
const issue = branch.split('/')[0];

const response = execSync(`hub pull-request -i ${issue} -b master -h ${branch}`, options);

console.log('Pull request link: ', response);
console.log('Pull request successfully created');