#! /usr/bin/env node

const { add, dec, inc } = require('../src/helpers/math');

const expect = (actual) => {
  return {
    toBe(expected) {
      if (actual !== expected) {
        throw new Error(`${actual} is not equal to ${expected}`);
      }
    }
  }
};

const test = (title, callback) => {
  try {
    callback();
    console.log(`✓ ${title}`);
  } catch (error) {
    console.error(`✕ ${title}`);
    console.error(error);
  }
};

let result;
let expected;

test('Add numbers', () => {
  result = add(3, 7);
  expected = 10;
  expect(result).toBe(expected)  
});
test('Decrease the number by one', () => {
  result = dec(10);
  expected = 9;
  expect(result).toBe(expected)  
});
test('Increase the number by one', () => {
  result = inc(10);
  expected = 11;
  expect(result).toBe(expected)  
});
